#include "robot/branding/branding_fingerprint.hpp"
#include "project_branding.hpp"  // generated by CMake into ${GENERATED_DIR}

extern "C" {
const char* g_brand_fingerprint = PROJECT_BRAND_FINGERPRINT;  // single definition
}

